dbt_dwh:
  outputs:
    trino_output:
      type: trino
      method: none
      user: maninblack
      database: iceberg
      host: trino-coordinator
      port: 8080
      schema: staging
      threads: 1
  target: trino_output